# UBC - KCDS

## PPDS

### Week 2
Instructor: Socorro Dominguez-Vidana

Overview:

- [] Show how to use `.loc` and `.iloc`
- [] Demonstrate how to rename columns of a dataframe using `.rename()`
- [] Create new or columns in a dataframe using `.assign()`.
- [] Drop columns in a dataframe using `.drop()`
- [] Use `df[]` to filter rows of a dataframe.
- [] Calculate summary statistics on grouped objects using `.groupby()` and `.agg()`.

Extras:
- [] Conditional Value Filling
- [] Plotting with Altair

### Using `pd.DataFrame()`

In [1]:
import pandas as pd

In [2]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [3]:
data = {'Animal': ['Falcon', 'Falcon', 'Parrot', 'Parrot'],
         'Food' : ['meat', 'meat', 'veggies', 'veggies'],
     'Max Speed': [380., 370., 24., 26.],
     'Min Speed': [120., 110., 5., 6.]}
data

{'Animal': ['Falcon', 'Falcon', 'Parrot', 'Parrot'],
 'Food': ['meat', 'meat', 'veggies', 'veggies'],
 'Max Speed': [380.0, 370.0, 24.0, 26.0],
 'Min Speed': [120.0, 110.0, 5.0, 6.0]}

We use `pd.DataFrame()` when we want to convert a dictionary or other data structure into a `pd.DataFrame`.

If we apply `pd.DataFrame()` to something that is already a `pd.DataFrame`, this is the equivalent of doing an **identity** operation (think of $1\times1$ or $1+0$)

In [4]:
df = pd.DataFrame(data)
df

   Animal     Food  Max Speed  Min Speed
0  Falcon     meat      380.0      120.0
1  Falcon     meat      370.0      110.0
2  Parrot  veggies       24.0        5.0
3  Parrot  veggies       26.0        6.0

In [5]:
df2 = pd.DataFrame(data)

In [6]:
type(df)

pandas.DataFrame

In [7]:
pd.DataFrame(df)

   Animal     Food  Max Speed  Min Speed
0  Falcon     meat      380.0      120.0
1  Falcon     meat      370.0      110.0
2  Parrot  veggies       24.0        5.0
3  Parrot  veggies       26.0        6.0

In [8]:
pd.DataFrame(df.loc[:, 'Animal'])

   Animal
0  Falcon
1  Falcon
2  Parrot
3  Parrot

`Tip!` Remember that whenever you see a *new** function, look at the documentation. The easiest way (for me) is to look in the browser. Type something as "pandas DataFrame documentation" in the browser and usually the first entry will be your best friend.

#### Data Frames: Their Methods and Attributes 
##### (The only thing you might need to know about OOP for now)
###### When to use `()` or not.

Before we can call an attribute or a method of an object, we need to know what type of object it is, that will determine what we can call. To learn about the type, we use the built-in function `type`

In [9]:
type(df)

pandas.DataFrame

- **Attributes** are just pieces of data that belong to an object — like a label stuck on it. Think of them as "what the object knows" or "what it has." You call them by using `.` and then the attribute.

- Example:
 If you have a data frame stored in the variable `df`, you can call its `shape` attribute by doing:

`df` + `.` + `shape`

In [10]:
df

   Animal     Food  Max Speed  Min Speed
0  Falcon     meat      380.0      120.0
1  Falcon     meat      370.0      110.0
2  Parrot  veggies       24.0        5.0
3  Parrot  veggies       26.0        6.0

In [11]:
df2.shape

(4, 4)

In [12]:
df.columns

Index(['Animal', 'Food', 'Max Speed', 'Min Speed'], dtype='str')

- **Methods** are functions that belong to an object — things the object can do.
For example, if we want a data frame object stored in `df` to describe itself, we call:  
`df` + `.` + `describe` + `()`

In [13]:
df.describe()

        Max Speed   Min Speed
count    4.000000    4.000000
mean   200.000000   60.250000
std    202.115479   63.352848
min     24.000000    5.000000
25%     25.500000    5.750000
50%    198.000000   58.000000
75%    372.500000  112.500000
max    380.000000  120.000000

We will learn more about functions in Module 4, for now, the parenthesis `()` is a way of giving extra information of what we need. For example, the method describe can be passed with an empty `()`, then it just brings **by default** the statistics of the numeric variables. If we wanted to extract more information, ie, the qualitative variables as well, we can pass the argument `include = all`

In [14]:
df.describe(include = 'all')

        Animal  Food   Max Speed   Min Speed
count        4     4    4.000000    4.000000
unique       2     2         NaN         NaN
top     Falcon  meat         NaN         NaN
freq         2     2         NaN         NaN
mean       NaN   NaN  200.000000   60.250000
std        NaN   NaN  202.115479   63.352848
min        NaN   NaN   24.000000    5.000000
25%        NaN   NaN   25.500000    5.750000
50%        NaN   NaN  198.000000   58.000000
75%        NaN   NaN  372.500000  112.500000
max        NaN   NaN  380.000000  120.000000

## The special indexing attributes `.iloc[]` and `.loc[]`

What happens if I need to extract one value?

In [15]:
df_desc = df.describe()
df_desc

        Max Speed   Min Speed
count    4.000000    4.000000
mean   200.000000   60.250000
std    202.115479   63.352848
min     24.000000    5.000000
25%     25.500000    5.750000
50%    198.000000   58.000000
75%    372.500000  112.500000
max    380.000000  120.000000

In [16]:
df_desc.loc['count', 'Max Speed']

np.float64(4.0)

`.loc[]` is a `pd.DataFrame` **attribute**. 
It looks a bit different, as it has the `[]` notation but that is because it is an indexer attribute, that means, we need to pass a `rows` and a `columns` location so that it can bring to us what values the data frame has at a specific position.

Select rows and columns based on `label`

The rule:

`df.loc[row]`

`df.loc[*row*, start:end:step]` or `df.loc[*row*, [labels]]`

`df.loc[:, 'column']`

For all rows, use `:`

In [17]:
df

   Animal     Food  Max Speed  Min Speed
0  Falcon     meat      380.0      120.0
1  Falcon     meat      370.0      110.0
2  Parrot  veggies       24.0        5.0
3  Parrot  veggies       26.0        6.0

In [18]:
df.loc[0, 'Max Speed']

np.float64(380.0)

In [19]:
df.loc[[0,1], 'Animal':'Min Speed':2]

   Animal  Max Speed
0  Falcon      380.0
1  Falcon      370.0

In [20]:
df.loc[[3, 2], ['Animal', 'Max Speed']]

   Animal  Max Speed
3  Parrot       26.0
2  Parrot       24.0

In [21]:
df.loc[:, 'Animal']

0    Falcon
1    Falcon
2    Parrot
3    Parrot
Name: Animal, dtype: str

**NOTE** Look at the cell above, it looks different, not as a data frame. When we only have one row or one column of information, the data type is not a Data Frame any more, it is a `pandas.Series`. `pandas.Series` have their own attributes and methods.

#### `.iloc[]`

Same as `.loc[]` but works with numeric index rather than label.

In [22]:
df

   Animal     Food  Max Speed  Min Speed
0  Falcon     meat      380.0      120.0
1  Falcon     meat      370.0      110.0
2  Parrot  veggies       24.0        5.0
3  Parrot  veggies       26.0        6.0

In [23]:
df.iloc[[1, 2], [1, 2]]

      Food  Max Speed
1     meat      370.0
2  veggies       24.0

##### Other attributes

Any `pandas.DataFrame` has:
- Attributes:
    - `.loc[]`
    - `.iloc[]`
    - `.shape`
    - `.columns`
    - `.dtypes`
    - `.index`
    - `.size`
    - etc...
- Methods:
    - `.group_by()`
    - `.sort_values()`
    - `.rename()`
    - `.assign()`
    - etc...

In [24]:
df.dtypes

Animal           str
Food             str
Max Speed    float64
Min Speed    float64
dtype: object

## Filtering

- `.loc[]` and `.iloc[]` can also be used as boolean indexers:

In [25]:
df

   Animal     Food  Max Speed  Min Speed
0  Falcon     meat      380.0      120.0
1  Falcon     meat      370.0      110.0
2  Parrot  veggies       24.0        5.0
3  Parrot  veggies       26.0        6.0

In [26]:
# We extract a mask of the rows where Animal is `Parrot`, a series of True and False values
df['Animal'] == 'Parrot'

0    False
1    False
2     True
3     True
Name: Animal, dtype: bool

In [27]:
# We place exactly that same condition inside our `.loc[]` to retrieve the rows
df.loc[df['Animal'] == 'Parrot']

   Animal     Food  Max Speed  Min Speed
2  Parrot  veggies       24.0        5.0
3  Parrot  veggies       26.0        6.0

When we have multiple conditions, we can use:

```python
df[(_____) & (_____)]
```

In [28]:
df2 = df.loc[(df['Max Speed'] > 320) & (df['Max Speed'] < 380)]
df2

   Animal  Food  Max Speed  Min Speed
1  Falcon  meat      370.0      110.0

#### Creating new columns or Overwriting columns with `.assign()`

1. Option A: With `.loc[]`

In [29]:
df

   Animal     Food  Max Speed  Min Speed
0  Falcon     meat      380.0      120.0
1  Falcon     meat      370.0      110.0
2  Parrot  veggies       24.0        5.0
3  Parrot  veggies       26.0        6.0

Task: Let's create a new column that gives the difference between Max speed - Min Speed.

In [30]:
df.assign(speed_diff = df.loc[:, 'Max Speed']-df.loc[:, 'Min Speed'])

   Animal     Food  Max Speed  Min Speed  speed_diff
0  Falcon     meat      380.0      120.0       260.0
1  Falcon     meat      370.0      110.0       260.0
2  Parrot  veggies       24.0        5.0        19.0
3  Parrot  veggies       26.0        6.0        20.0

**Caution** If we call the df varaible again, you will see that your result is not being saved / stored.

In [31]:
df

   Animal     Food  Max Speed  Min Speed
0  Falcon     meat      380.0      120.0
1  Falcon     meat      370.0      110.0
2  Parrot  veggies       24.0        5.0
3  Parrot  veggies       26.0        6.0

In order to save the result, we need to overwrite the variable `df` or save it in a new variable, for notebook hygene, we simply overwrite our variable.

In [32]:
# Note that there is no output after running this cell
df = df.assign(speed_diff = df.loc[:, 'Max Speed']-df.loc[:, 'Min Speed'])

In [33]:
# Note tht when we call the variable, the new column is there.
df

   Animal     Food  Max Speed  Min Speed  speed_diff
0  Falcon     meat      380.0      120.0       260.0
1  Falcon     meat      370.0      110.0       260.0
2  Parrot  veggies       24.0        5.0        19.0
3  Parrot  veggies       26.0        6.0        20.0

2. Option B: Without `.loc[]`  
Sometimes, we like to save some characters to keep the code more human readable.

In [34]:
df.loc[:,'Max Speed'] #df['Max Speed'] exactly the same

0    380.0
1    370.0
2     24.0
3     26.0
Name: Max Speed, dtype: float64

In [35]:
df['Max Speed']

0    380.0
1    370.0
2     24.0
3     26.0
Name: Max Speed, dtype: float64

In [36]:
df = df.assign(speed_diff2 = df['Max Speed']-df['Min Speed'])
df

   Animal     Food  Max Speed  Min Speed  speed_diff  speed_diff2
0  Falcon     meat      380.0      120.0       260.0        260.0
1  Falcon     meat      370.0      110.0       260.0        260.0
2  Parrot  veggies       24.0        5.0        19.0         19.0
3  Parrot  veggies       26.0        6.0        20.0         20.0

Cases where `assign` will not work:

```python
df = df.assign(Diff Speed = df['Max Speed']-df['Min Speed'])
```

You can still do:
```python
df.assign(**{'Diff Speed': df['Max Speed'] - df['Min Speed']})
```
But that's tricky and hard to remember... In this cases, do not use `.assign()`

In [37]:
df.assign(**{'Diff Speed' : df['Max Speed']-df['Min Speed']})

   Animal     Food  Max Speed  Min Speed  speed_diff  speed_diff2  Diff Speed
0  Falcon     meat      380.0      120.0       260.0        260.0       260.0
1  Falcon     meat      370.0      110.0       260.0        260.0       260.0
2  Parrot  veggies       24.0        5.0        19.0         19.0        19.0
3  Parrot  veggies       26.0        6.0        20.0         20.0        20.0

#### Creating new columns or Overwriting columns without `.assign()`

In [38]:
# On the left side of the `=`, you must have the df[col] of where you want to assign the new value. 
df['Diff Speed3'] = df['Max Speed'] - df['Min Speed']

In [39]:
df['Max Speed'] - df['Min Speed']

0    260.0
1    260.0
2     19.0
3     20.0
dtype: float64

Very common error:

```python
df = df['Max Speed']-df['Min Speed']
```
The above would overwrite the whole data frame to only one series, ie you will lose everything exept that new column.

**be careful,** when not using `assign()`, make sure that you are only modifying one column:

```python
df['Speed Diff'] = df['Max Speed']-df['Min Speed']
```

#### Why do I sometimes see double square brackets `[[]]`?

The symbols `[]` have two uses:
- list()
- Indexing attributes

Right now, we just saw the indexing attribute. But sometimes you may see the following:
`df[['Animal', 'Food']]`

Here, the outside `[]` is the indexer attribute we have been studying.

The inside `[]` is a `list` and the main idea is that sometimes, you want to put a collection of columns together inside the `indexer` but if you just placed the items, pandas gets confused as to why we have so many arguments. To "cheat" the system, we place them inside a "box" or a "list". Don't worry too much about this now, but be aware of the difference.

In [40]:
pd.DataFrame(df['Animal'])

   Animal
0  Falcon
1  Falcon
2  Parrot
3  Parrot

In [41]:
# I create a list called cols
cols = ['Animal', 'Max Speed']
cols

['Animal', 'Max Speed']

In [42]:
# I pass it inside my `.loc[]`
df.loc[:, cols]

   Animal  Max Speed
0  Falcon      380.0
1  Falcon      370.0
2  Parrot       24.0
3  Parrot       26.0

In [43]:
# By substitution, this is the same as doing:
df.loc[:, ['Animal', 'Max Speed']]

   Animal  Max Speed
0  Falcon      380.0
1  Falcon      370.0
2  Parrot       24.0
3  Parrot       26.0

In [44]:
# And we saw that sometimes we are lazy and save some characters, so we can summarize to:
df[['Animal', 'Max Speed']] #= df.loc[rows, columns]

   Animal  Max Speed
0  Falcon      380.0
1  Falcon      370.0
2  Parrot       24.0
3  Parrot       26.0

#### `.drop()`
We use this to get rid of columns we do not need anymore.

In [45]:
df

   Animal     Food  Max Speed  Min Speed  speed_diff  speed_diff2  Diff Speed3
0  Falcon     meat      380.0      120.0       260.0        260.0        260.0
1  Falcon     meat      370.0      110.0       260.0        260.0        260.0
2  Parrot  veggies       24.0        5.0        19.0         19.0         19.0
3  Parrot  veggies       26.0        6.0        20.0         20.0         20.0

In [46]:
df.drop(columns = 'Diff Speed3')

   Animal     Food  Max Speed  Min Speed  speed_diff  speed_diff2
0  Falcon     meat      380.0      120.0       260.0        260.0
1  Falcon     meat      370.0      110.0       260.0        260.0
2  Parrot  veggies       24.0        5.0        19.0         19.0
3  Parrot  veggies       26.0        6.0        20.0         20.0

In [47]:
df

   Animal     Food  Max Speed  Min Speed  speed_diff  speed_diff2  Diff Speed3
0  Falcon     meat      380.0      120.0       260.0        260.0        260.0
1  Falcon     meat      370.0      110.0       260.0        260.0        260.0
2  Parrot  veggies       24.0        5.0        19.0         19.0         19.0
3  Parrot  veggies       26.0        6.0        20.0         20.0         20.0

In [48]:
# We need to overwrite the variable to see changes.
df = df.drop(columns = 'Diff Speed3')

In [49]:
df

   Animal     Food  Max Speed  Min Speed  speed_diff  speed_diff2
0  Falcon     meat      380.0      120.0       260.0        260.0
1  Falcon     meat      370.0      110.0       260.0        260.0
2  Parrot  veggies       24.0        5.0        19.0         19.0
3  Parrot  veggies       26.0        6.0        20.0         20.0

As an alternative, instead of overwriting the variable, we can use the parameter `inplace = True`
```python
df.drop(columns = 'Diff Speed3', inplace=True)
```

In [50]:
# Dropping more than one column
df.drop(columns = ['Max Speed', 'Min Speed'])

   Animal     Food  speed_diff  speed_diff2
0  Falcon     meat       260.0        260.0
1  Falcon     meat       260.0        260.0
2  Parrot  veggies        19.0         19.0
3  Parrot  veggies        20.0         20.0

### Renaming with `.rename()`

In [51]:
df

   Animal     Food  Max Speed  Min Speed  speed_diff  speed_diff2
0  Falcon     meat      380.0      120.0       260.0        260.0
1  Falcon     meat      370.0      110.0       260.0        260.0
2  Parrot  veggies       24.0        5.0        19.0         19.0
3  Parrot  veggies       26.0        6.0        20.0         20.0

In [52]:
df = df.rename(columns = {'Max Speed':'max_speed', 
                          'Min Speed':'min_speed'})
df

   Animal     Food  max_speed  min_speed  speed_diff  speed_diff2
0  Falcon     meat      380.0      120.0       260.0        260.0
1  Falcon     meat      370.0      110.0       260.0        260.0
2  Parrot  veggies       24.0        5.0        19.0         19.0
3  Parrot  veggies       26.0        6.0        20.0         20.0

#### `.groupby()`

In [53]:
df

   Animal     Food  max_speed  min_speed  speed_diff  speed_diff2
0  Falcon     meat      380.0      120.0       260.0        260.0
1  Falcon     meat      370.0      110.0       260.0        260.0
2  Parrot  veggies       24.0        5.0        19.0         19.0
3  Parrot  veggies       26.0        6.0        20.0         20.0

In [54]:
group_df = df.groupby('Animal')
group_df

In [55]:
# It is a different data type, so it has different attributes and methods
type(group_df)

pandas.api.typing.DataFrameGroupBy

In [56]:
group_df.groups

{'Falcon': [0, 1], 'Parrot': [2, 3]}

In [57]:
group_df.get_group('Falcon')

   Animal  Food  max_speed  min_speed  speed_diff  speed_diff2
0  Falcon  meat      380.0      120.0       260.0        260.0
1  Falcon  meat      370.0      110.0       260.0        260.0

**What does that even mean??**

![img](https://miro.medium.com/max/1206/0*5Zzcwe-rlxz-EQ_N)

In [58]:
df.groupby('Animal')

In [59]:
# This cannot be computed because 'Food' has words, so pandas cannot calculate the mean of words.
df.groupby('Animal').mean()

TypeError: dtype 'str' does not support operation 'mean'

In [60]:
# But it can sum them - look that it concatenates them
df.groupby('Animal').sum()

                  Food  max_speed  min_speed  speed_diff  speed_diff2
Animal
Falcon        meatmeat      750.0      230.0       520.0        520.0
Parrot  veggiesveggies       50.0       11.0        39.0         39.0

`.reset_index()`  
When we group by, the column we used to group, becomes an index, this makes it a bit harder to get the information if we still need it, so sometimes, we reset the index so that Animal is back to the columns section.

In [61]:
df.groupby('Animal').sum().reset_index()

   Animal            Food  max_speed  min_speed  speed_diff  speed_diff2
0  Falcon        meatmeat      750.0      230.0       520.0        520.0
1  Parrot  veggiesveggies       50.0       11.0        39.0         39.0

In [62]:
# If we want to compute different operations for different columns, we can use `agg` instead of the set of given functions:
# Note that we do not use `[]` when calling `'max'`
df.groupby('Animal').agg({'max_speed': 'max', 
                           'min_speed': 'max'}).reset_index()

   Animal  max_speed  min_speed
0  Falcon      380.0      120.0
1  Parrot       26.0        6.0

In [63]:
# If we want to compute multiple operations per different columns, we can use `[]` as a list
# Note that we pass 'sum' and 'mean' inside `[]`
df3 = df.groupby('Animal').agg({'max_speed':['sum', 'mean'], 
                                 'min_speed': ['max', 'min']}).reset_index()
df3

   Animal max_speed        min_speed
                sum   mean       max    min
0  Falcon     750.0  375.0     120.0  110.0
1  Parrot      50.0   25.0       6.0    5.0

Look at the two data frames above. Notice that when we pass things inside a `list []`, we create a double column index. 

Because of this, it is adviced that if you are only calling one operation, do not put it as a list.

Chaining sometimes is useful. But it can be stressful, the best way is do one step at a time until you are comfortable. Look at all the changes little by little, for now, it doesn't matter how many Jupyter cells you need:

In [64]:
df.groupby('Animal')

In [65]:
df.groupby('Animal').agg(['sum', 'count'])

                  Food       max_speed       min_speed       speed_diff        \
                   sum count       sum count       sum count        sum count
Animal
Falcon        meatmeat     2     750.0     2     230.0     2      520.0     2
Parrot  veggiesveggies     2      50.0     2      11.0     2       39.0     2

       speed_diff2
               sum count
Animal
Falcon       520.0     2
Parrot        39.0     2

In [66]:
df.groupby('Animal').agg(['sum', 'count']).loc[:,'max_speed']

          sum  count
Animal
Falcon  750.0      2
Parrot   50.0      2

In [67]:
df.groupby('Animal').agg(['sum', 'count']).loc[:,'max_speed'].reset_index()

   Animal    sum  count
0  Falcon  750.0      2
1  Parrot   50.0      2

#### A Fancier & More Efficient Way?

In [68]:
df.groupby('Animal').agg(
    sum = ('max_speed','mean'),
    count = ('max_speed','sum'),
).reset_index()

   Animal    sum  count
0  Falcon  375.0  750.0
1  Parrot   25.0   50.0

There exist multiple ways of doing the same thing; be creative and share as much as you wish in Piazza. Discuss interesting ways you found to get to a result.

**About Grading: The tests are *mostly* a guide.**

We cannot make very strict tests. 
- Inhibit your creativity. 

We cannot make very lenient tests.
- Cannot test your output

Tests are based on:
- An ideal of best practices
- Tidy data (more on this next week)
- A bit of hand holding to make your life in future questions "easier"
- Beginner friendly skills (if you are a pro, you might find them quite limiting) 

However, if you get `Success`, that means you will get the point - as long as you have restarted your Kernel and verified that things run well from Top to Bottom.

**Disclaimer:**
If you want the full mark, you need to pass the test.

How?

Read the bottom part of the error messages, you might find them helpful.


#### Summary

##### What we did?

- [x] Show how to use `.loc` and `.iloc`
- [x] Demonstrate how to rename columns of a dataframe using .rename()
- [x] Create new or columns in a dataframe using .assign() notation.
- [x] Drop columns in a dataframe using .drop()
- [x] Use df[] notation to filter rows of a dataframe.
- [x] Calculate summary statistics on grouped objects using .groupby() and .agg().

### Appendix I
#### Plotting with Altair

**Altair** is a declarative statistical visualization library in Python that is built on the principles of the **[Grammar of Graphics](https://towardsdatascience.com/a-comprehensive-guide-to-the-grammar-of-graphics-for-effective-visualization-of-multi-dimensional-1f92b4ed4149)**. Here is a brief overview of its logic:

*Basic Components*
- Data: The dataset you want to visualize, typically provided as a Pandas DataFrame.
- Mark: The geometric shape used to represent data points (e.g., bar, point, line).
- Encoding: The mapping of data attributes (columns) to visual properties (e.g., x-axis, y-axis, color, size).

**Steps to Create a Visualization**

In [69]:
df

   Animal     Food  max_speed  min_speed  speed_diff  speed_diff2
0  Falcon     meat      380.0      120.0       260.0        260.0
1  Falcon     meat      370.0      110.0       260.0        260.0
2  Parrot  veggies       24.0        5.0        19.0         19.0
3  Parrot  veggies       26.0        6.0        20.0         20.0

In [74]:
#Import Altair and load your data:
import altair as alt

df = df.groupby('Animal').agg(
    mean = ('max_speed','mean'),
    count = ('max_speed','sum'),
).reset_index()
df

   Animal   mean  count
0  Falcon  375.0  750.0
1  Parrot   25.0   50.0

In [75]:
# Initialize a Chart: Create a basic chart object by passing the data.
chart = alt.Chart(df)

In [76]:
#chart

In [77]:
# Add a Mark: Specify the type of mark to use.
chart = chart.mark_bar()

In [78]:
# Add encodings
chart = chart.encode(
    x='Animal:O',  # O for ordinal
    y='mean:Q'      # Q for quantitative
)

In [79]:
# Render the Chart: Display the chart.
# You can also do: chart.display()
chart

alt.Chart(...)

In [80]:
df

   Animal   mean  count
0  Falcon  375.0  750.0
1  Parrot   25.0   50.0

In one chunk of code:

In [81]:
import altair as alt

In [82]:
chart = alt.Chart(df).mark_bar().encode(
    x='Animal:O',  # O for ordinal
    y='mean:Q'      # Q for quantitative
)
chart

alt.Chart(...)

Try different marks: `.mark_line()`, `.mark_point()`, `.mark_tick()`