# UBC - KCDS

## PPDS

### Week 3
Instructor: Socorro Dominguez-Vidana

- [] Explain what **tidy data** is.
- [] Use `.melt()` and `.pivot()` / `.pivot_table()`
- [] Learn how to reset a data frame's index.
- [] Combine data frames using `.merge()` and `.concat()`

## Tidy Data

- The concept stems from a [paper](https://vita.had.co.nz/papers/tidy-data.pdf) written by Hadley Wickham in 2014.
- We tidy our data to create a standard across multiple analysis tools.

Rules for Tidy Data:

* each row is a single observation,
* each column is a single variable, and
* each value is a single cell (i.e., its entry in the data frame is not shared with another value).

![](https://datasciencebook.ca/_main_files/figure-html/02-obs-1.png)

## What to do when data is not tidy...

Data sometimes comes in tables that are easy to read/make sense for humans.

- However, they are not necessarily in the best format for computations to happen.

Most common scenarios:
- We need to convert from Wide to Long tables
- We need to convert from Long to Wide tables

## Wide to Long

## Goal

![](https://datasciencebook.ca/img/wrangling/pivot_functions.001.png)

A common task:
- Get data into a tidy format by combining values that are stored in separate columns, but are really part of the same variable, into one.
- Data is often stored this way because this format is sometimes more intuitive for human readability.

- The format above on the left would be difficult to use when performing data visualization or statistical analysis. To find the latest year, we would need to work with the column names; it would be more challenging if you wanted to find the value for the population for a given region for the latest year. In the right format, this becomes very straight forward.

- We also do not know what the values on the left really represent: land? population? We solve it with the format on the right.

## From Long to Wide

![](https://datasciencebook.ca/img/wrangling/pivot_functions.002.png)

- In the previous figure, the table on the left is in an untidy, long format because:
- The **values** of the variable **region** are stored as column names and not easily accessible.
- The **type values** are spread across multiple columns, which will prevent us from doing any desired visualization or statistical tasks.
- **Remember:** one of the criteria for tidy data is that each observation must be in a single row.
- We can still get the information out from the "wrong" format. However, it would be more challenging.

### How to Manipulate Long and Wide Tables In Python

### Melt

> wide to long format

[Documentation](https://pandas.pydata.org/docs/reference/api/pandas.melt.html)

![](https://pandas.pydata.org/docs/_images/reshaping_melt.png)

In [1]:
import pandas as pd

cereal = pd.read_csv('https://raw.githubusercontent.com/UBC-MDS/programming-in-python-for-data-science/master/data/cereal.csv')
cereal = cereal.drop(labels=['type', 'shelf', 'weight', 'cups', 'rating'], axis=1)
cereal.head()

,name,mfr,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins
0,100% Bran,N,70,4,1,130,10.0,5.0,6,280,25
1,100% Natural Bran,Q,120,3,5,15,2.0,8.0,8,135,0
2,All-Bran,K,70,4,1,260,9.0,7.0,5,320,25
3,All-Bran with Extra Fiber,K,50,4,0,140,14.0,8.0,0,330,25
4,Almond Delight,R,110,2,2,200,1.0,14.0,8,1,25

In [2]:
cereal['name'].value_counts()

name
100% Bran                    1
100% Natural Bran            1
All-Bran                     1
All-Bran with Extra Fiber    1
Almond Delight               1
                            ..
Triples                      1
Trix                         1
Wheat Chex                   1
Wheaties                     1
Wheaties Honey Gold          1
Name: count, Length: 77, dtype: int64

In [3]:
cereal_long = cereal.melt(id_vars=['name', 'mfr'])
cereal_long

                          name mfr  variable  value
0                    100% Bran   N  calories   70.0
1            100% Natural Bran   Q  calories  120.0
2                     All-Bran   K  calories   70.0
3    All-Bran with Extra Fiber   K  calories   50.0
4               Almond Delight   R  calories  110.0
..                         ...  ..       ...    ...
688                    Triples   G  vitamins   25.0
689                       Trix   G  vitamins   25.0
690                 Wheat Chex   R  vitamins   25.0
691                   Wheaties   G  vitamins   25.0
692        Wheaties Honey Gold   G  vitamins   25.0

[693 rows x 4 columns]

In [4]:
cereal_long[cereal_long['name'] == '100% Bran']

          name mfr  variable  value
0    100% Bran   N  calories   70.0
77   100% Bran   N   protein    4.0
154  100% Bran   N       fat    1.0
231  100% Bran   N    sodium  130.0
308  100% Bran   N     fiber   10.0
385  100% Bran   N     carbo    5.0
462  100% Bran   N    sugars    6.0
539  100% Bran   N    potass  280.0
616  100% Bran   N  vitamins   25.0

### Pivot

> long to wide

[Documentation](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pivot.html)


![](https://pandas.pydata.org/docs/_images/reshaping_pivot.png)

In [5]:
lego = pd.read_csv('https://raw.githubusercontent.com/UBC-MDS/programming-in-python-for-data-science/master/data/lego_untidy.csv')
lego.head()

  set_num                          name  year  lego_info  value
0    00-1               Weetabix Castle  1970   theme_id    414
1    00-1               Weetabix Castle  1970  num_parts    471
2    00-2  Weetabix Promotional House 1  1976  num_parts    147
3    00-2  Weetabix Promotional House 1  1976   theme_id    413
4    00-3  Weetabix Promotional House 2  1976  num_parts    149

In [6]:
lego_tidy = lego.pivot(index='set_num',
                       columns='lego_info',
                       values='value')
lego_tidy.reset_index()

lego_info       set_num  num_parts  theme_id
0                  00-1        471       414
1                  00-2        147       413
2                  00-3        149       413
3                  00-4        126       413
4                  00-6          3        67
...                 ...        ...       ...
11668      tominifigs-1          2        50
11669        trucapam-1         71       598
11670          tsuper-1          3        12
11671           vwkit-1         22       366
11672           wwgp1-1          3       476

[11673 rows x 3 columns]

In [7]:
lego_tidy = lego.pivot(index=['set_num', 'name'],
                       columns='lego_info',
                       values='value')
lego_tidy.head().reset_index()

lego_info set_num                           name  num_parts  theme_id
0            00-1                Weetabix Castle        471       414
1            00-2   Weetabix Promotional House 1        147       413
2            00-3   Weetabix Promotional House 2        149       413
3            00-4  Weetabix Promotional Windmill        126       413
4            00-6                  Special Offer          3        67

In [8]:
lego_tidy2 = lego_tidy.reset_index()
lego_tidy2

lego_info,set_num,name,num_parts,theme_id
0,00-1,Weetabix Castle,471,414
1,00-2,Weetabix Promotional House 1,147,413
2,00-3,Weetabix Promotional House 2,149,413
3,00-4,Weetabix Promotional Windmill,126,413
4,00-6,Special Offer,3,67
...,...,...,...,...
11668,tominifigs-1,Town Minifig Packs 2-Pack,2,50
11669,trucapam-1,Captain America Mosaic,71,598
11670,tsuper-1,Technic Super Set,3,12
11671,vwkit-1,Volkswagen Kit,22,366
11672,wwgp1-1,Wild West Limited Edition Gift Pack,3,476

In [9]:
# What if I want to use only the name?
lego.pivot(index='name',
           columns='lego_info',
           values='value')

ValueError: Index contains duplicate entries, cannot reshape

## What duplicates?

### How do I find them?

In [10]:
lego_tidy.reset_index().value_counts('name').head()

name
Basic Building Set        55
Universal Building Set    32
Basic Set                 23
Helicopter                23
Fire Station              14
Name: count, dtype: int64

In [11]:
bbset = lego[lego['name'] == 'Basic Building Set']
bbset

      set_num                name  year  lego_info  value
30      010-3  Basic Building Set  1968  num_parts     77
31      010-3  Basic Building Set  1968   theme_id    366
32      011-1  Basic Building Set  1968  num_parts    145
33      011-1  Basic Building Set  1968   theme_id    366
34      022-1  Basic Building Set  1968  num_parts    110
...       ...                 ...   ...        ...    ...
15727   730-2  Basic Building Set  1985  num_parts    432
15842   735-1  Basic Building Set  1990  num_parts    538
15843   735-1  Basic Building Set  1990   theme_id    467
15846   740-1  Basic Building Set  1985  num_parts    530
15847   740-1  Basic Building Set  1985   theme_id    467

[110 rows x 5 columns]

In [12]:
# Show with lego too
bbset.pivot(index=['set_num','name'],
                       columns='lego_info',
                       values='value')

lego_info                    num_parts  theme_id
set_num  name
010-3    Basic Building Set         77       366
011-1    Basic Building Set        145       366
022-1    Basic Building Set        110       366
033-2    Basic Building Set        177       366
044-1    Basic Building Set        225       366
055-2    Basic Building Set        256       366
066-1    Basic Building Set        407       366
1106-2   Basic Building Set        413       470
120438-1 Basic Building Set        176       469
1562-2   Basic Building Set         36       467
1676-1   Basic Building Set         22       467
1679-1   Basic Building Set         43       467
1922-2   Basic Building Set         60       469
1962-1   Basic Building Set        219       467
1964-1   Basic Building Set         27       467
1965-1   Basic Building Set         38       469
303-1    Basic Building Set         33       467
304-1    Basic Building Set         31       467
308-2    Basic Building Set         34       467
310-4    Basic Building Set         46       467
315-1    Basic Building Set         62       467
317-2    Basic Building Set         68       467
320-1    Basic Building Set         78       467
325-1    Basic Building Set        109       467
327-1    Basic Building Set        107       467
330-1    Basic Building Set        158       467
335-1    Basic Building Set        245       467
337-1    Basic Building Set        225       467
340-1    Basic Building Set        220       467
347-2    Basic Building Set        330       467
350-2    Basic Building Set        315       467
4122-1   Basic Building Set        201       470
503-1    Basic Building Set         39       467
504-1    Basic Building Set         41       467
507-1    Basic Building Set         60       467
508-1    Basic Building Set         66       467
510-1    Basic Building Set        102       467
515-1    Basic Building Set        115       467
517-1    Basic Building Set        123       467
520-16   Basic Building Set        173       467
525-1    Basic Building Set        185       467
527-1    Basic Building Set        196       467
530-1    Basic Building Set        273       467
535-1    Basic Building Set        349       467
537-1    Basic Building Set        271       467
540-1    Basic Building Set        619       467
547-1    Basic Building Set        624       467
550-1    Basic Building Set        578       467
557-1    Basic Building Set        721       467
715-1    Basic Building Set        410       467
720-1    Basic Building Set        339       467
725-1    Basic Building Set        440       467
730-2    Basic Building Set        432       467
735-1    Basic Building Set        538       467
740-1    Basic Building Set        530       467

What if I do not care about the `set_num`, just about the `name`?

### Alternative: Use `pivot_table`

In [13]:
bbset.head()

   set_num                name  year  lego_info  value
30   010-3  Basic Building Set  1968  num_parts     77
31   010-3  Basic Building Set  1968   theme_id    366
32   011-1  Basic Building Set  1968  num_parts    145
33   011-1  Basic Building Set  1968   theme_id    366
34   022-1  Basic Building Set  1968  num_parts    110

In [14]:
bbset2 = lego.pivot_table(index='name',
           columns='lego_info',
           values='value') #, aggfunc='mean').reset_index()
bbset2 = bbset2.reset_index()
bbset2

lego_info                              name  num_parts  theme_id
0                 1 stud Blue Storage Brick        0.0     501.0
1           Scenery and Dagger Trap polybag       25.0     435.0
2                                   Spectre        7.0     552.0
3                  White Spaceman Key Chain        0.0     503.0
4                 'Where Are My Pants?' Guy        6.0     549.0
...                                     ...        ...       ...
10365               {Red Race Car Number 3}       39.0      82.0
10366              {Roadplates and Scenery}       85.0     533.0
10367                    {Rock Saw Vehicle}       22.0     442.0
10368                       {Town Vehicles}      158.0     533.0
10369                          {Yellow Cab}       44.0      22.0

[10370 rows x 3 columns]

In [15]:
bbset2[bbset2['name']=="Basic Building Set"]

lego_info                name   num_parts    theme_id
1663       Basic Building Set  216.672727  454.363636

In [16]:
bbset

      set_num                name  year  lego_info  value
30      010-3  Basic Building Set  1968  num_parts     77
31      010-3  Basic Building Set  1968   theme_id    366
32      011-1  Basic Building Set  1968  num_parts    145
33      011-1  Basic Building Set  1968   theme_id    366
34      022-1  Basic Building Set  1968  num_parts    110
...       ...                 ...   ...        ...    ...
15727   730-2  Basic Building Set  1985  num_parts    432
15842   735-1  Basic Building Set  1990  num_parts    538
15843   735-1  Basic Building Set  1990   theme_id    467
15846   740-1  Basic Building Set  1985  num_parts    530
15847   740-1  Basic Building Set  1985   theme_id    467

[110 rows x 5 columns]

In [17]:
bbset.shape

(110, 5)

In [18]:
bbset.pivot(index=['set_num', 'name'],
                       columns='lego_info',
                       values='value').reset_index()['num_parts'].mean()

np.float64(216.6727272727273)

In [19]:
bbset.pivot(index=['set_num', 'name'],
                       columns='lego_info',
                       values='value').reset_index()['theme_id'].mean()

np.float64(454.3636363636364)

## Merging Data Frames

In [20]:
df = pd.DataFrame({'animal': ['Falcon', 'Falcon',
                              'Parrot', 'Parrot'],
                   'id' : [1, 2, 1, 2],
                   'speed': [390., 370., 24., 26.]})

df_food = pd.DataFrame({'animal': ['Falcon', 'Falcon',
                                   'Parrot', 'Parrot'],
                        'id' : [1, 2, 1, 2],
                        'food': ['kibble', 'meat', 'seeds', 'fruits']})

In [21]:
df

   animal  id  speed
0  Falcon   1  390.0
1  Falcon   2  370.0
2  Parrot   1   24.0
3  Parrot   2   26.0

In [22]:
df_food

   animal  id    food
0  Falcon   1  kibble
1  Falcon   2    meat
2  Parrot   1   seeds
3  Parrot   2  fruits

In [23]:
df.merge(df_food, on = 'animal')

   animal  id_x  speed  id_y    food
0  Falcon     1  390.0     1  kibble
1  Falcon     1  390.0     2    meat
2  Falcon     2  370.0     1  kibble
3  Falcon     2  370.0     2    meat
4  Parrot     1   24.0     1   seeds
5  Parrot     1   24.0     2  fruits
6  Parrot     2   26.0     1   seeds
7  Parrot     2   26.0     2  fruits

In [24]:
df.merge(df_food, on = ['animal', 'id'])

   animal  id  speed    food
0  Falcon   1  390.0  kibble
1  Falcon   2  370.0    meat
2  Parrot   1   24.0   seeds
3  Parrot   2   26.0  fruits

In [25]:
df.merge(df_food, on = ['animal', 'id'], how='left')

   animal  id  speed    food
0  Falcon   1  390.0  kibble
1  Falcon   2  370.0    meat
2  Parrot   1   24.0   seeds
3  Parrot   2   26.0  fruits

In [26]:
df = pd.DataFrame({'Animal': ['Falcon', 'Falcon',
                              'Parrot', 'Parrot'],
                   'ID' : [1, 2, 1, 2],
                   'Speed': [380, 370, 24, 26]})
df_food = pd.DataFrame({'animal': ['Falcon', 'Falcon',
                                   'Parrot', 'Parrot',
                                   'Tiger'],
                        'id' : [1, 2, 1, 2, 1],
                        'food': ['kibble', 'meat', 'seeds', 'fruits', 'meat']})

In [27]:
df

   Animal  ID  Speed
0  Falcon   1    380
1  Falcon   2    370
2  Parrot   1     24
3  Parrot   2     26

In [28]:
df_food

   animal  id    food
0  Falcon   1  kibble
1  Falcon   2    meat
2  Parrot   1   seeds
3  Parrot   2  fruits
4   Tiger   1    meat

In [29]:
df.merge(df_food, left_on = ['Animal', 'ID'], right_on = ['animal', 'id'], how='outer', indicator=True)

   Animal   ID  Speed  animal  id    food      _merge
0  Falcon  1.0  380.0  Falcon   1  kibble        both
1  Falcon  2.0  370.0  Falcon   2    meat        both
2  Parrot  1.0   24.0  Parrot   1   seeds        both
3  Parrot  2.0   26.0  Parrot   2  fruits        both
4     NaN  NaN    NaN   Tiger   1    meat  right_only

## Difference with Concat

In [30]:
df

   Animal  ID  Speed
0  Falcon   1    380
1  Falcon   2    370
2  Parrot   1     24
3  Parrot   2     26

In [31]:
df_food

   animal  id    food
0  Falcon   1  kibble
1  Falcon   2    meat
2  Parrot   1   seeds
3  Parrot   2  fruits
4   Tiger   1    meat

In [32]:
df1 = pd.concat([df, df_food])
df1

   Animal   ID  Speed  animal   id    food
0  Falcon  1.0  380.0     NaN  NaN     NaN
1  Falcon  2.0  370.0     NaN  NaN     NaN
2  Parrot  1.0   24.0     NaN  NaN     NaN
3  Parrot  2.0   26.0     NaN  NaN     NaN
0     NaN  NaN    NaN  Falcon  1.0  kibble
1     NaN  NaN    NaN  Falcon  2.0    meat
2     NaN  NaN    NaN  Parrot  1.0   seeds
3     NaN  NaN    NaN  Parrot  2.0  fruits
4     NaN  NaN    NaN   Tiger  1.0    meat

In [33]:
df1.loc[3, 'ID']

3    2.0
3    NaN
Name: ID, dtype: float64

In [34]:
df_food.columns

Index(['animal', 'id', 'food'], dtype='str')

In [35]:
df.columns

Index(['Animal', 'ID', 'Speed'], dtype='str')

In [36]:
df.columns = df_food.columns

In [37]:
df_food.columns

Index(['animal', 'id', 'food'], dtype='str')

In [38]:
df_ = pd.concat([df, df_food])
df_

   animal  id    food
0  Falcon   1     380
1  Falcon   2     370
2  Parrot   1      24
3  Parrot   2      26
0  Falcon   1  kibble
1  Falcon   2    meat
2  Parrot   1   seeds
3  Parrot   2  fruits
4   Tiger   1    meat

In [39]:
df_.loc[3, 'food']

3        26
3    fruits
Name: food, dtype: object

In [40]:
df_.dtypes

animal       str
id         int64
food      object
dtype: object

### Concatenating sideways ("merging" by position?)

In [41]:
df3 = pd.concat([df_food, df], axis = 1, verify_integrity=True)
df3

ValueError: Indexes have overlapping values: Index(['animal', 'id', 'food'], dtype='str')

#### Disadvantages of Concat

You may end up with duplicated column names - this will prevent you from some operations.

In [43]:
df3 = pd.concat([df_food, df], axis = 1)
df3[df3['animal'] == 'Parrot']

ValueError: cannot reindex on an axis with duplicate labels